site_name: Avery Broadbent

nav:
    - Home: index.md
    - Showcase:
        - Sound: audio.md
        - Music: music.md
        - Engineering: engineering.md
    - Projects: https://corviscape.itch.io

theme:
    name: simple-blog
    sidebar: true
    navigation_depth: 3
    components:
        title: false
